In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [8]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [9]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.mean()))

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [18]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [21]:
#  creating new column
labels = ['Young Adult', 'Adult','Middle-aged', 'Senior']
# df['age_group'] = pd.qcut(df['age'], bins=[0, 25, 40, 60, 100], labels=labels)
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [22]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged

In [23]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [25]:
# new column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Anually': 365,
    'Every 3 months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [26]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged,NaN

In [27]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                      NaN               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                      NaN               Annually
9                     90.0              Quarterly

In [28]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [29]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [ ]:
df = df.drop(columns=['promo_code_used'], axis=1)
# axis = 1 is used to specify that we want to drop a column, not a row. By default, drop() assumes you want to drop rows (axis=0), so we need to set axis=1 to indicate that we're dropping a column.

In [31]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binaryNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading psycopg2_binary-2.9.11-cp311-cp311-win_amd64.whl (2.7 MB)
                                              0.0/2.7 MB ? eta -:--:--
                                              0.0/2.7 MB ? eta -:--:--
                                              0.0/2.7 MB ? eta -:--:--
     -                                        0.1/2.7 MB 1.2 MB/s eta 0:00:03
     -                                        0.1/2.7 MB 939.4 kB/s eta 0:00:03
     --                                       0.1/2.7 MB 774.0 kB/s eta 0:00:04
     --                                       0.1/2.7 MB 774.0 kB/s eta 0:00:04
     ----                                     0.3/2.7 MB 1.2 MB/s eta 0:00:02
     -----                                    0.4/2.7 MB 1.3 MB/s eta 0:00:02
     ------                                   0.4/2.7 MB 1.3 MB/s eta 0:00:02
     ------                                   0.4/2.7 MB 1.3 MB/s eta 0:00:02
     --------                                 0.6/2.7 MB 1.2 MB/s eta 0:00:02
     --------                                 0.6/2.7 MB 1.2 MB/s eta 0:00:02
     --------                                 0.6/2.7 MB 1.2 MB/s eta 0:00:02
     ---------                                0.7/2.7 MB 1.1 MB/s eta 0:00:02
     ----------                               0.7/2.7 MB 1.1 MB/s eta 0:00:02
     ----------                               0.7/2.7 MB 1.1 MB/s eta 0:00:02
     -----------                              0.7/2.7 MB 1.0 MB/s eta 0:00:02
     -----------                              0.7/2.7 MB 1.0 MB/s eta 0:00:02
     -----------                              0.7/2.7 MB 1.0 MB/s eta 0:00:02
     ------------                             0.8/2.7 MB 965.6 kB/s eta 0:00:02
     ------------                             0.8/2.7 MB 959.6 kB/s eta 0:00:02
     ------------                             0.8/2.7 MB 959.6 kB/s eta 0:00:02
     -------------                            0.9/2.7 MB 911.4 kB/s eta 0:00:02
     -------------                            0.9/2.7 MB 911.4 kB/s eta 0:00:02
     -------------                            0.9/2.7 MB 911.4 kB/s eta 0:00:02
     --------------                           1.0/2.7 MB 846.5 kB/s eta 0:00:03
     --------------                           1.0/2.7 MB 841.5 kB/s eta 0:00:03
     --------------                           1.0/2.7 MB 841.5 kB/s eta 0:00:03
     --------------                           1.0/2.7 MB 792.7 kB/s eta 0:00:03
     ---------------                          1.0/2.7 MB 778.8 kB/s eta 0:00:03
     ---------------                          1.0/2.7 MB 778.8 kB/s eta 0:00:03
     ---------------                          1.1/2.7 MB 756.1 kB/s eta 0:00:03
     ----------------                         1.1/2.7 MB 745.9 kB/s eta 0:00:03
     ----------------                         1.1/2.7 MB 745.9 kB/s eta 0:00:03
     ----------------                         1.1/2.7 MB 745.9 kB/s eta 0:00:03
     ----------------                         1.1/2.7 MB 713.8 kB/s eta 0:00:03
     ----------------                         1.1/2.7 MB 713.8 kB/s eta 0:00:03
     ----------------                         1.1/2.7 MB 713.8 kB/s eta 0:00:03
     -----------------                        1.2/2.7 MB 672.9 kB/s eta 0:00:03
     -----------------                        1.2/2.7 MB 672.7 kB/s eta 0:00:03
     -----------------                        1.2/2.7 MB 672.7 kB/s eta 0:00:03
     ------------------                       1.2/2.7 MB 655.2 kB/s eta 0:00:03
     ------------------                       1.3/2.7 MB 650.2 kB/s eta 0:00:03
     ------------------                       1.3/2.7 MB 650.2 kB/s eta 0:00:03
     ------------------                       1.3/2.7 MB 650.2 kB/s eta 0:00:03
     -------------------                      1.3/2.7 MB 635.7 kB/s eta 0:00:03
     -------------------                      1.4/2.7 MB 640.6 kB/s eta 0:00:03
     -------------------                      1.4/2.7 MB 640.6 kB/s eta 0:00:03
     --------------------                     1.4/2.7 MB 632.2 kB/s eta 0:00:03
     --------------------                     1.4/2.7 MB 632.2 kB/s eta 0:00:03
     --------------------                     1.4/2.7 MB 632.2 kB/s eta 0:00:03
     ---------------------                    1.5/2.7 MB 624.6 kB/s eta 0:00:03
     ---------------------                    1.5/2.7 MB 624.6 kB/s eta 0:00:03
     ---------------------                    1.5/2.7 MB 624.6 kB/s eta 0:00:03
     ----------------------                   1.5/2.7 MB 609.7 kB/s eta 0:00:02
     ----------------------                   1.5/2.7 MB 609.7 kB/s eta 0:00:02
     ----------------------                   1.5/2.7 MB 609.7 kB/s eta 0:00:02
     ----------------------                   1.5/2.7 MB 584.8 kB/s eta 0:00:03
     -----------------------                  1.6/2.7 MB 589.4 kB/s eta 0:00:02
     -----------------------                  1.6/2.7 MB 589.4 kB/s eta 0:00:02
     -----------------------                  1.6/2.7 MB 573.8 kB/s eta 0:00:02
     -----------------------                  1.6/2.7 MB 571.7 kB/s eta 0:00:02
     -----------------------                  1.6/2.7 MB 571.7 kB/s eta 0:00:02
     ------------------------                 1.6/2.7 MB 566.7 kB/s eta 0:00:02
     ------------------------                 1.7/2.7 MB 558.3 kB/s eta 0:00:02
     ------------------------                 1.7/2.7 MB 558.3 kB/s eta 0:00:02
     -------------------------                1.7/2.7 MB 551.8 kB/s eta 0:00:02
     -------------------------                1.7/2.7 MB 549.4 kB/s eta 0:00:02
     -------------------------                1.7/2.7 MB 550.5 kB/s eta 0:00:02
     -------------------------                1.7/2.7 MB 550.5 kB/s eta 0:00:02
     -------------------------                1.8/2.7 MB 541.4 kB/s eta 0:00:02
     --------------------------               1.8/2.7 MB 540.4 kB/s eta 0:00:02
     --------------------------               1.8/2.7 MB 540.4 kB/s eta 0:00:02
     --------------------------               1.8/2.7 MB 534.5 kB/s eta 0:00:02
     ---------------------------              1.8/2.7 MB 533.3 kB/s eta 0:00:02
     ---------------------------              1.8/2.7 MB 533.3 kB/s eta 0:00:02
     ---------------------------              1.9/2.7 MB 527.8 kB/s eta 0:00:02
     ----------------------------             1.9/2.7 MB 529.5 kB/s eta 0:00:02
     ----------------------------             1.9/2.7 MB 529.5 kB/s eta 0:00:02
     ----------------------------             1.9/2.7 MB 524.9 kB/s eta 0:00:02
     -----------------------------            2.0/2.7 MB 526.5 kB/s eta 0:00:02
     -----------------------------            2.0/2.7 MB 526.5 kB/s eta 0:00:02
     -----------------------------            2.0/2.7 MB 521.6 kB/s eta 0:00:02
     ------------------------------           2.0/2.7 MB 521.1 kB/s eta 0:00:02
     ------------------------------           2.0/2.7 MB 521.1 kB/s eta 0:00:02
     ------------------------------           2.0/2.7 MB 521.1 kB/s eta 0:00:02
     ------------------------------           2.1/2.7 MB 519.7 kB/s eta 0:00:02
     -------------------------------          2.1/2.7 MB 521.2 kB/s eta 0:00:02
     -------------------------------          2.1/2.7 MB 521.2 kB/s eta 0:00:02
     -------------------------------          2.2/2.7 MB 517.9 kB/s eta 0:00:02
     --------------------------------         2.2/2.7 MB 524.3 kB/s eta 0:00:01
     ---------------------------------        2.3/2.7 MB 532.9 kB/s eta 0:00:01
     ----------------------------------       2.3/2.7 MB 539.1 kB/s eta 0:00:01
     -----------------------------------      2.4/2.7 MB 547.4 kB/s eta 0:00:01
     ------------------------------------     2.5/2.7 MB 557.8 kB/s eta 0:00:01
     -------------------------------------    2.5/2.7 MB 565.7 kB/s eta 0:00:01
     --------------------------------------   2.6/2.7 MB 571.2 kB/s eta 0:00:01
     --------------------------------------   2.6/2.7 MB 574.0 kB/s eta 0:00:01
     ---------------------------------------  2.7/2.7 MB 581.8 kB/s eta 0:00:01
     ---------------------------------------- 2.7/2.7 MB 582.6 kB/s eta 0:00:00
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp311-cp311-win_amd64.whl (2.1 MB)
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
     -                                        0.1/2.1 MB 762.6 kB/s eta 0:00:03
     --                                       0.1/2.1 MB 722.1 kB/s eta 0:00:03
     --                                       0.1/2.1 MB 722.1 kB/s eta 0:00:03
     ---                                      0.2/2.1 MB 778.2 kB/s eta 0:00:03
     ----                                     0.3/2.1 MB 787.7 kB/s eta 0:00:03
     -----                                    0.3/2.1 MB 798.7 kB/s eta 0:00:03
     ------                                   0.3/2.1 MB 846.5 kB/s eta 0:00:03
     -------                                  0.4/2.1 MB 867.0 kB/s eta 0:00:03
     -------                                  0.4/2.1 MB 846.3 kB/s eta 0:00:03
     --------                                 0.5/2.1 MB 842.4 kB/s eta 0:00:02
     ---------                                0.5/2.1 MB 850.4 kB/s eta 0:00:02
     ----------                               0.6/2.1 MB 846.7 kB/s eta 0:00:02
     ----------                               0.6/2.1 MB 853.3 kB/s eta 0:00:02
     -----------                              0.6/2.1 MB 868.8 kB/s eta 0:00:02
     ------------                             0.7/2.1 MB 882.3 kB/s eta 0:00:02
     -------------                            0.7/2.1 MB 870.1 kB/s eta 0:00:02
     --------------                           0.8/2.1 MB 882.1 kB/s eta 0:00:02
     ---------------                          0.8/2.1 MB 892.9 kB/s eta 0:00:02
     ----------------                         0.9/2.1 MB 891.8 kB/s eta 0:00:02
     -----------------                        0.9/2.1 MB 901.1 kB/s eta 0:00:02
     -----------------                        1.0/2.1 MB 909.6 kB/s eta 0:00:02
     ------------------                       1.0/2.1 MB 911.9 kB/s eta 0:00:02
     -------------------                      1.1/2.1 MB 924.4 kB/s eta 0:00:02
     --------------------                     1.1/2.1 MB 934.9 kB/s eta 0:00:02
     ---------------------                    1.2/2.1 MB 929.4 kB/s eta 0:00:02
     ----------------------                   1.2/2.1 MB 943.3 kB/s eta 0:00:01
     ------------------------                 1.3/2.1 MB 963.9 kB/s eta 0:00:01
     -------------------------                1.3/2.1 MB 979.5 kB/s eta 0:00:01
     --------------------------               1.4/2.1 MB 990.5 kB/s eta 0:00:01
     ---------------------------              1.5/2.1 MB 1.0 MB/s eta 0:00:01
     ----------------------------             1.5/2.1 MB 1.0 MB/s eta 0:00:01
     -----------------------------            1.6/2.1 MB 1.0 MB/s eta 0:00:01
     -------------------------------          1.7/2.1 MB 1.0 MB/s eta 0:00:01
     -------------------------------          1.7/2.1 MB 1.0 MB/s eta 0:00:01
     -------------------------------          1.7/2.1 MB 1.0 MB/s eta 0:00:01
     -------------------------------          1.7/2.1 MB 1.0 MB/s eta 0:00:01
     ---------------------------------        1.8/2.1 MB 969.1 kB/s eta 0:00:01
     ---------------------------------        1.8/2.1 MB 961.2 kB/s eta 0:00:01
     -----------------------------------      1.9/2.1 MB 980.3 kB/s eta 0:00:01
     ------------------------------------     2.0/2.1 MB 980.6 kB/s eta 0:00:01
     -------------------------------------    2.0/2.1 MB 1.0 MB/s eta 0:00:01
     ---------------------------------------  2.1/2.1 MB 1.0 MB/s eta 0:00:01
     ---------------------------------------- 2.1/2.1 MB 1.0 MB/s eta 0:00:00
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.4.0-cp311-cp311-win_amd64.whl (238 kB)
                                              0.0/238.2 kB ? eta -:--:--
     ----------                              61.4/238.2 kB 1.7 MB/s eta 0:00:01
     ----------------------                 143.4/238.2 kB 2.1 MB/s eta 0:00:01
     -----------------------------------    225.3/238.2 kB 1.7 MB/s eta 0:00:01
     -------------------------------------- 238.2/238.2 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\praja\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.12.2)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy
Successfully installed greenlet-3.4.0 psycopg2-binary-2.9.11 sqlalchemy-2.0.49


Q1: What is the total revenue generated by male vs. female customers?

Q2: Which customers used a discount but still spent more than the average purchase amount?

Q3: Which are the top 5 products with the highest average review rating?

Q4: Compare the average Purchase Amounts between Standard and Express Shipping.

Q5: Do subscribed customers spend more? (Comparison of average spend and total revenue between subscribers and non-subscribers).

Q6: Which 5 products have the highest percentage of purchases with discounts applied?

Q7: Segment customers into "New," "Returning," and "Loyal" based on their total number of previous purchases, and show the count of each segment.

Q8: What are the top 3 most purchased products within each category?

Q9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

Q10: What is the revenue contribution of each age group?

In [33]:
from sqlalchemy import create_engine

# step 1 - connect to the database
from sqlalchemy import create_engine


username = 'postgres'
password = '1234567890'
host = 'localhost'
port = '5433'
database = 'customer_behavior'

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')


# step 2 - write the dataframe to the database
table_name = 'customer'
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"DataFrame has been written to the '{table_name}' table in the '{database}' database.")

DataFrame has been written to the 'customer' table in the 'customer_behavior' database.